apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashpod3
  name: ashpod3
spec:
  containers:
  - image: dockerashu/ashuoracleweb:v2
    name: ashpod3
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
