apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashusvc1
  name: ashusvc1
spec:
  ports:
  - name: "1234"
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    x: ashupod1
  type: NodePort
status:
  loadBalancer: {}
