apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashupod3svc
  name: ashupod3svc
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
   run: ashpod3
  type: NodePort
status:
  loadBalancer: {}
