apiVersion: v1   #   thiis  api  version  for  pod only
kind: Pod      #  like  pod  there  are  so many things  pod can have one container 
metadata:
 name: ashupod1   #  it must  be  uoique  across the cluster 
 labels:
  x: ashupod1

spec:             #   this will  will  about  containers 
 containers:
  - image: nginx
    name: ashuc1   #  you can give same  name of container
    ports:
     - containerPort: 80  #  it will be same as dockerifle  expose port 
